"""Export analysis results as an HTML report."""


def generate_html_report(results: list[dict], filename: str = "SparsileX Report") -> str:
    """Generate a self-contained HTML report from analysis results."""
    rows_html = ""
    for r in results:
        stats = r.get("statistics", {})
        test_name = r.get("test_display_name", r.get("test_name", "Analysis"))
        apa = r.get("apa_text", "")

        # Stats rows
        stat_rows = ""
        for k, v in stats.items():
            if isinstance(v, (list, dict)):
                continue
            stat_rows += f"<tr><td>{k}</td><td>{v}</td></tr>"

        # Plots
        plots_html = ""
        for plot in r.get("plots", []):
            plots_html += f'<div class="plot"><h4>{plot["title"]}</h4><img src="data:image/png;base64,{plot["image_base64"]}" /></div>'

        # Code
        code = r.get("code", {})
        code_html = ""
        if code:
            code_html = f"""
            <div class="code-section">
                <h4>Python</h4><pre>{code.get("python", "")}</pre>
                <h4>R</h4><pre>{code.get("r", "")}</pre>
            </div>"""

        rows_html += f"""
        <div class="result">
            <h3>{test_name}</h3>
            {f'<p class="apa">{apa}</p>' if apa else ''}
            <table>{stat_rows}</table>
            {plots_html}
            {code_html}
        </div>"""

    return f"""<!DOCTYPE html>
<html>
<head>
<title>{filename}</title>
<style>
    body {{ font-family: -apple-system, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; background: #0a0a0a; color: #ddd; }}
    h1 {{ color: #818cf8; border-bottom: 2px solid #333; padding-bottom: 10px; }}
    h3 {{ color: #c4b5fd; margin-top: 30px; }}
    .result {{ border: 1px solid #333; border-radius: 8px; padding: 20px; margin: 20px 0; background: #111; }}
    .apa {{ font-style: italic; color: #999; background: #1a1a1a; padding: 12px; border-radius: 4px; }}
    table {{ width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 14px; }}
    td {{ padding: 6px 12px; border-bottom: 1px solid #222; }}
    td:first-child {{ color: #888; }}
    td:last-child {{ text-align: right; font-family: monospace; }}
    .plot img {{ max-width: 100%; border-radius: 4px; }}
    pre {{ background: #1a1a1a; padding: 12px; border-radius: 4px; overflow-x: auto; font-size: 12px; color: #aaa; }}
    .code-section h4 {{ font-size: 12px; color: #666; margin: 10px 0 4px; }}
    .footer {{ text-align: center; color: #444; margin-top: 40px; font-size: 12px; }}
</style>
</head>
<body>
<h1>{filename}</h1>
<p style="color:#666">Generated by SparsileX</p>
{rows_html}
<div class="footer">SparsileX — AI-Native Statistical Analysis</div>
</body>
</html>"""
